version: '2.1'

services:
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    image: eureka-server
    ports:
      - 8761:8761
    healthcheck:
      test: "exit 0"

  config-service:
    build: config-server/
    restart: always
    network_mode: "host"
    image: config-service
    hostname: localhost
    ports:
      - 8888:8888
    healthcheck:
      test: "exit 0"

  zuul-api:
    build: zuul-api/
    depends_on:
      - config-service
      - eureka-server
    restart: always
    network_mode: "host"
    image: zuul-api
    hostname: localhost
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"

  mongo:
    image: mongo:latest

    ports:
      - 27017:27017
    expose:
      - 27017
    container_name: mongo
    network_mode: host
    hostname: localhost
    restart: always
    healthcheck:
      test: "exit 0"

  user:
    build: user/
    depends_on:
      - mongo
    restart: always
    network_mode: host
    container_name: userregistration
    image: user
    hostname: localhost
    ports:
      - 8088:8088
    healthcheck:
      test: "exit 0"

  neo4j:
    build: neo4j/
    depends_on:
      - mongo
    restart: always
    network_mode: host
    container_name: neo4j
    image: neo4j
    hostname: localhost
    ports:
      - 8090:8090
    healthcheck:
      test: "exit 0"


