# my global config
global:
 scrape_interval:     15s # Set the scrape interval to every 15 zseconds. Default is every 1 minute.
 evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
 # scrape_timeout is set to the global default (10s).
# Alertmanager configuration
alerting:
 alertmanagers:
 - static_configs:
   - targets:
     # - alertmanager:9093
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
 # - "first_rules.yml"
 # - "second_rules.yml"
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
 # The job name is added as a label job=<job_name> to any timeseries scraped from this config.
 # - job_name: 'prometheus'
 #   metrics_path: 'actuator/prometheus'
 #   static_configs:
 #   - targets: ['localhost:9090']
 - job_name: 'config-server'
   metrics_path: 'actuator/prometheus'
   static_configs:
   - targets: ['13.126.224.142:8888']
 - job_name: 'consumer-service'
   metrics_path: 'actuator/prometheus'
   static_configs:
   - targets: ['13.126.224.142:8190']
 - job_name: 'designer-service'
   metrics_path: 'actuator/prometheus'
   static_configs:
   - targets: ['13.126.224.142:8187']
 - job_name: 'eureka-server'
   metrics_path: 'actuator/prometheus'
   static_configs:
   - targets: ['13.126.224.142:8761']
 - job_name: 'login-service'
   metrics_path: 'actuator/prometheus'
   static_configs:
   - targets: ['13.126.224.142:8193']
 - job_name: 'manufacturer-service'
   metrics_path: 'actuator/prometheus'
   static_configs:
   - targets: ['13.126.224.142:8189']
 - job_name: 'reports-service'
   metrics_path: 'actuator/prometheus'
   static_configs:
   - targets: ['13.126.224.142:8195']
 - job_name: 'supplier-service'
   metrics_path: 'actuator/prometheus'
   static_configs:
   - targets: ['13.126.224.142:8188']
 - job_name: 'user-service'
   metrics_path: 'actuator/prometheus'
   static_configs:
   - targets: ['13.126.224.142:8192']
 - job_name: 'workflow-service'
   metrics_path: 'actuator/prometheus'
   static_configs:
   - targets: ['13.126.224.142:8194']
 - job_name: 'zuul-api'
